Rename stopped to running (and reverse sense).
This has the subtle side effect of preventing attempts to do anything
when the profiling hook is still active after Python's global module
destruction has replaced all globals with `None`.

This caused errors to be printed at the end of pytest runs, e.g.

Exception AttributeError: "'NoneType' object has no attribute 'get'" in <function _remove at 0x100737758> ignored